#!/bin/sh
. "$(dirname -- "$0")/_lib.sh"

PY_IMAGE=python:3.12.14-slim@sha256:09f7da3bc104798d0afb40bc08d23ab2da20a76130cec1f2ef170848f5d85217
CADDY_IMAGE=caddy:2.11.4-alpine@sha256:5f5c8640aae01df9654968d946d8f1a56c497f1dd5c5cda4cf95ab7c14d58648

command -v docker >/dev/null || die "docker is not installed"

FROM_STDIN=0
case "${1:-}" in
	"") ;;
	--from-stdin) FROM_STDIN=1 ;;
	*) die "usage: generate-secrets.sh [--from-stdin]" ;;
esac

STTY_SAVED=""
if [ "$FROM_STDIN" = "0" ] && [ -t 0 ]; then
	STTY_SAVED=$(stty -g 2>/dev/null || echo "")
fi
restore_tty() {
	if [ -n "$STTY_SAVED" ]; then stty "$STTY_SAVED" 2>/dev/null || true; fi
}
trap restore_tty EXIT INT TERM HUP

read_secret() {   # $1 = prompt; echoes the value
	if [ "$FROM_STDIN" = "1" ]; then
		IFS= read -r _value
		printf '%s' "$_value"
		return 0
	fi
	[ -t 0 ] || die "no terminal to read a password from.
For an automated test, and only for that, use --from-stdin."
	printf '%s: ' "$1" >&2
	stty -echo
	IFS= read -r _value
	stty echo
	printf '\n' >&2
	printf '%s' "$_value"
}

read_confirmed() {   # $1 = prompt
	while :; do
		_a=$(read_secret "$1")
		[ -n "$_a" ] || { echo "empty; try again" >&2; continue; }
		if [ "$FROM_STDIN" = "1" ]; then printf '%s' "$_a"; return 0; fi
		_b=$(read_secret "$1 (again)")
		if [ "$_a" = "$_b" ]; then printf '%s' "$_a"; return 0; fi
		echo "they do not match; try again" >&2
	done
}

if [ "$FROM_STDIN" = "0" ]; then
	cat <<'INTRO'
Two passwords are needed.

  1. The SHARED password. Everyone in the room is given this one, and it stays
     in force for the whole exercise. Write it on the board.
  2. The FACILITATOR password. Yours. It opens the console that starts the
     session, grades the written answers and exports the results.

Neither is stored anywhere in plain text. Only their hashes are written.
INTRO
fi

BASIC_PW=$(read_confirmed "Shared password for the room")
FAC_PW=$(read_confirmed "Facilitator password")
[ "$BASIC_PW" != "$FAC_PW" ] || die "use two different passwords: the shared one
is written on a whiteboard, and the facilitator one grades the exercise."

say "hashing (scrypt takes a moment on purpose)"

FAC_HASH=$(printf '%s' "$FAC_PW" | docker run --rm -i "$PY_IMAGE" python -c '
import hashlib, secrets, string, sys
pw = sys.stdin.buffer.read()
alphabet = string.ascii_letters + string.digits
salt = "".join(secrets.choice(alphabet) for _ in range(16))
n, r, p = 32768, 8, 1
digest = hashlib.scrypt(pw, salt=salt.encode(), n=n, r=r, p=p,
                        maxmem=132 * n * r * p, dklen=64).hex()
print("scrypt:%d:%d:%d$%s$%s" % (n, r, p, salt, digest))
') || die "could not compute the facilitator hash"

BASIC_HASH=$(printf '%s\n' "$BASIC_PW" | docker run --rm -i "$CADDY_IMAGE" \
	caddy hash-password) || die "could not compute the Basic Auth hash"

SECRET_KEY=$(docker run --rm "$PY_IMAGE" python -c \
	'import secrets; print(secrets.token_urlsafe(48))') || die "could not generate a secret key"

case "$FAC_HASH" in
	scrypt:*'$'*'$'*) ;;
	*) die "the facilitator hash came back in an unexpected shape" ;;
esac
case "$BASIC_HASH" in
	'$2'*) ;;
	*) die "the Basic Auth hash came back in an unexpected shape" ;;
esac

quote() {
	case "$1" in
		*"'"*) die "a value contains a single quote, which cannot be written
inertly into $ENV_FILE. Choose a password without one." ;;
	esac
	printf "'%s'" "$1"
}

if [ -e "$ENV_FILE" ]; then
	backup="$ENV_FILE.$(date -u +%Y%m%dT%H%M%SZ).bak"
	cp "$ENV_FILE" "$backup"
	chmod 600 "$backup"
	say "the existing $ENV_FILE was kept as $backup"
fi

SITE=${SECCAP_SITE_ADDRESS:-}
if [ "$FROM_STDIN" = "0" ]; then
	printf 'Domain to serve from (e.g. seccap.example.org): ' >&2
	IFS= read -r SITE
fi
[ -n "$SITE" ] || SITE="seccap.example.org"
case "$SITE" in
	*sakura-vpn-update*) die "that domain is the COMPROMISED infrastructure in the
scenario. Serving the platform from it would erase the distinction three
missions exist to teach. Use a different one." ;;
esac

umask 077
{
	echo "# Generated by deploy/generate-secrets.sh. Do not commit."
	echo "#"
	echo "# THIS FILE IS EXECUTED AS SHELL by deploy/_lib.sh. Every value is"
	echo "# single-quoted so that it is inert: no expansion, no substitution,"
	echo "# nothing that runs. If you edit it, keep it that way, and put"
	echo "# nothing in it but generated or controlled values."
	echo ""
	echo "SECCAP_SITE_ADDRESS=$(quote "$SITE")"
	echo "SECCAP_BASIC_AUTH_USER=$(quote "${SECCAP_BASIC_AUTH_USER:-seccap}")"
	echo "SECCAP_BASIC_AUTH_HASH=$(quote "$BASIC_HASH")"
	echo "SECCAP_SECRET_KEY=$(quote "$SECRET_KEY")"
	echo "SECCAP_FACILITATOR_PASSWORD_HASH=$(quote "$FAC_HASH")"
	echo "SECCAP_DEFAULT_LANG='ja'"
	echo "SECCAP_JOIN_RPM='60'"
	echo "SECCAP_IMAGE_TAG='rc'"
} > "$ENV_FILE"
chmod 600 "$ENV_FILE"

"$(command -v python3 || command -v python)" "$DEPLOY_DIR/validate_env.py" "$ENV_FILE" \
	|| die "the file just written would not pass validation; nothing will load it"

(
	set -a
	. "$ENV_FILE"
	set +a
	[ "$SECCAP_FACILITATOR_PASSWORD_HASH" = "$FAC_HASH" ] \
		|| { echo "the facilitator hash did not survive being written" >&2; exit 1; }
	[ "$SECCAP_BASIC_AUTH_HASH" = "$BASIC_HASH" ] \
		|| { echo "the Basic Auth hash did not survive being written" >&2; exit 1; }
	[ "$SECCAP_SECRET_KEY" = "$SECRET_KEY" ] \
		|| { echo "the secret key did not survive being written" >&2; exit 1; }
) || die "the values were altered on the way into $ENV_FILE"

say ""
say "wrote $ENV_FILE (mode 600)"
say "  site           $SITE"
say "  basic auth     ${SECCAP_BASIC_AUTH_USER:-seccap} / <the shared password>"
say "  facilitator    scrypt hash, ${#FAC_HASH} characters"
say ""
say "Nothing above was echoed, logged, or passed on a command line."
say "Write the shared password on the board; keep the facilitator one."
