PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no

PermitRootLogin no

X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no

MaxAuthTries 3
LoginGraceTime 30
MaxSessions 4

ClientAliveInterval 300
ClientAliveCountMax 2

AllowUsers seccap
